### ISSUE TITLE
Add Bullroarer test server

### ISSUE THREAD

**Issue by dt192** [westrany/Lotro-Server-Status-Discord-Bot#3]
Add Bullroarer test server

http://gls-bullroarer.lotro.com/GLS.DataCenterServer/StatusServer.aspx?s=10.192.160.61

**Comment by westrany** [comment]
Done in getting-monitor-to-work branch, will soon merge to main

**Comment by westrany** [comment]
![image](https://github.com/user-attachments/assets/fbaea0d7-5b09-4de2-808b-9d9483a2735f)
